name: changa_lab
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  awesome_dialog: ^3.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.0.15
  dio: ^5.5.0+1
  pin_code_fields: ^8.0.1
  connectivity_plus: ^6.0.3
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  file_picker: ^8.0.6
  image_picker: ^1.0.1
  cool_dropdown: ^2.1.0
  flutter_widget_from_html: ^0.15.1
  permission_handler: ^11.3.1
  flutter_inappwebview: ^5.8.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  open_file: ^3.3.2
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/social/
    - assets/svg/
    - assets/animation/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
