// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQhum5SqRYhF0G3-KkktqSTpjgf7y0Aw',
    appId: '1:564208810966:web:5bb39a21e5463966274277',
    messagingSenderId: '564208810966',
    projectId: 'changalab-57d47',
    authDomain: 'changalab-57d47.firebaseapp.com',
    storageBucket: 'changalab-57d47.appspot.com',
    measurementId: 'G-SBZK3CMNGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwZiJwGzeJtpRT54uKeaHpfUWMnRAOTkQ',
    appId: '1:378216189334:android:8bed6775f985391c54a1b7',
    messagingSenderId: '378216189334',
    projectId: 'changalab-2553b',
    storageBucket: 'changalab-2553b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOMK7AYGCBVFNBfNpAFInA4rr5DFVxZg',
    appId: '1:378216189334:ios:e834ae45d66ecaeb54a1b7',
    messagingSenderId: '378216189334',
    projectId: 'changalab-2553b',
    storageBucket: 'changalab-2553b.appspot.com',
    iosBundleId: 'dev.vlab.changalab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtOMK7AYGCBVFNBfNpAFInA4rr5DFVxZg',
    appId: '1:378216189334:ios:e834ae45d66ecaeb54a1b7',
    messagingSenderId: '378216189334',
    projectId: 'changalab-2553b',
    storageBucket: 'changalab-2553b.appspot.com',
    iosBundleId: 'dev.vlab.changalab',
  );

}